name: demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  audioplayers: ^0.20.0
  better_player: ^0.0.82
  camera: ^0.9.7+1
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.3
  ffmpeg_kit_flutter: ^4.5.1-LTS
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_svg: any
  flutter_video_info: ^1.2.0
  fluttertoast: ^8.0.8
  gallery_saver: ^2.3.2
  path: ^1.8.0
  path_provider: ^2.0.5
  video_player: ^2.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
dependency_overrides:
  camera_android: 0.9.7+1
  camera_avfoundation: 0.9.7+1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
